name: PDF Compilation

on:
  push:
    branches: [ master ]


jobs:
  compile_pdf:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

    - name: I4.0 Concept PDF Compilation
      run: |
        npm install -g markdown-pdf
        markdown-pdf -f A4 -s assets/css/main.css CertifiedByGs1-I40.md

    - name: Save PDF
      uses: actions/upload-artifact@v1
      with:
        name: Certified-by-GS1-Concepts
        path: CertifiedByGs1-I40.pdf

    - name: Trust Model PDF Compilation
      uses: docker://asciidoctor/docker-asciidoctor:latest
      with:
        entrypoint: asciidoctor-pdf
        args: -a icons=font -a source-highlighter=coderay CertifiedByGs1-Trust.adoc

    - name: Save PDF
      uses: actions/upload-artifact@v1
      with:
        name: Certified-by-GS1-Concepts
        path: CertifiedByGs1-Trust.pdf

