name: markdown-compile

on:
  push:
    branches: [ master ]


jobs:
  compile_pdf:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

    - name: Compile PDF
      run: |
        npm install -g markdown-pdf
        markdown-pdf certified-by-gs1-i40-one-pager.md

    - name: Save PDF
      uses: actions/upload-artifact@v1
      with:
        name: certified-by-gs1-i40-one-pager.pdf
        path: certified-by-gs1-i40-one-pager.pdf
