on:
  release:
    types:
      - created

name: Release PDF

jobs:
  build:
    name: compile and upload pdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
      - name: Compile I 4.0 Concept PDF
        run: |
          npm install -g markdown-pdf
          markdown-pdf -f A4 -s assets/css/main.css -m '{"html":true, "breaks":false}' CertifiedByGs1-I40.md
          ls -lah ./CertifiedByGs1-I40.pdf

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./CertifiedByGs1-I40.pdf
          asset_name: CertifiedByGs1-I40.pdf
          asset_content_type: application/pdf

      - name: Trust Model PDF Compilation
        uses: docker://asciidoctor/docker-asciidoctor:latest
        with:
          entrypoint: asciidoctor-pdf
          args: -a icons=font -a source-highlighter=coderay CertifiedByGs1-Trust.adoc

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./CertifiedByGs1-Trust.pdf
          asset_name: CertifiedByGs1-Trust.pdf
          asset_content_type: application/pdf
